version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: mvn clean
      - run: mvn test -s settings.xml
      - run: mvn package -s settings.xml
      - run: mvn install -s settings.xml
      - run: mvn deploy -DmuleDeploy -s settings.xml		
